package lk.ijse.finalproject.dao;

public enum DAOTypes {
    CUSTOMER, EMPLOYEE,EXPENSES, GRN,MRN, MIN,ORDER,ORDER_DETAIL,QUERY,STOCK,
    SUPPLIER,CASHIER, STOREKEEPER,MANAGER,RETURNITEMS,PURCHASE_ORDER, QUOTATION,INCOME;
}
