package lk.ijse.finalproject.util;

public enum Routes {
    LOGIN, DASHBOARD, USERNAME_ERROR, PASSWORD_ERROR,PASSWORD_RESET,MANAGEMENT_NOTES,
    MANAGE_EMPLOYEE, VIEW_NOTES, VIEW_STATISTICS,PROFILE_SETTINGS,LOGOUT,HAMBURGER, CLICKED_HAMBURGER,
    ADD_EMPLOYEE, CLICK_DASHBOARD, CLICK_MANAGE_EMPLOYEE, CLICK_VIEW_NOTES,HAM_MANAGE_EMPLOYEE,
    CLICK_VIEW_STATISTICS, CLICK_PROFILE_SETTINGS, CLICK_LOGOUT,CLICK_HAM_MANAGE_EMPLOYEE,
    STORE_DASHBOARD,CLICK_HAM_DASHBOARD,INVENTORY, SUPPLIER_DIRECTORY, CLICK_HAM_SUPPLIER_DIRECTORY,SUPPLIER_ACCOUNT,STORE_NOTES,CLICK_STORE_NOTES, STORE_STATISTICS,STORE_PROFILE,STORE_LOGOUT,
    NEW_STOCK, EDIT_STOCK_DETAILS,CREATE_MRN,HAM_STORE, CLICK_HAM_STORE, HAM_SUPPLIER, CLICK_HAM_SUPPLIER,
    CASHIER_DASHBOARD,ITEM,NEW_CUSTOMER,INCOME,EXPENSES, QUOTATION, PURCHASE_ORDER,RETURNS;
}
