package lk.ijse.finalproject.bo.custom;

public enum BOTypes {
    CUSTOMER, EMPLOYEE,SUPPLIER,STOCK,EXPENSES,ORDER, ORDER_DETAIL,MANAGER, STOREKEEPER, CASHIER, MRN,MIN, GRN,QUOTATION, PURCHASE_ORDER,RETURNS;
}
